---
permalink: api/reference_element_api_getsnmpstate.html 
sidebar: sidebar 
keywords: snmp,state,get,getting,getsnmpstate 
summary: È possibile utilizzare il metodo GetSnmpState per ottenere lo stato corrente della funzionalità SNMP. 
---
= GetSnmpState
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il `GetSnmpState` metodo per ottenere lo stato corrente della funzione SNMP.



[[parameters]]
== Parametri

Questo metodo non ha parametri di input.



[[return-values]]
== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===
| Nome | Descrizione | Tipo 


 a| 
attivato
 a| 
Valori possibili:

* vero
* falso


Il valore predefinito è false. Restituisce true se i nodi nel cluster sono configurati per SNMP.
 a| 
booleano



 a| 
snmpV3Enabled
 a| 
Valori possibili:

* vero
* falso


Il valore predefinito è false. Restituisce true se i nodi nel cluster sono configurati per SNMP v3.
 a| 
booleano

|===


[[request-example]]
== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "GetSnmpState",
  "params": {},
  "id" : 1
}
----


[[response-example]]
== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id" : 1,
  "result" : {
   "enabled": true,
   "snmpV3Enabled": false
   }
}
----


[[new-since-version]]
== Novità dalla versione

9,6



[[find-more-information]]
== Trova ulteriori informazioni

xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL]
