---
permalink: api/reference_element_api_deletekeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,deleting,delete 
summary: 'È possibile utilizzare il metodo DeleteKeyServerKmip per eliminare un Key Management Interoperability Protocol (KMIP) server di chiavi esistente. È possibile eliminare un server chiavi a meno che non sia l"ultimo assegnato al proprio provider e il provider non stia fornendo chiavi attualmente in uso.' 
---
= DeleteKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi utilizzare questo `DeleteKeyServerKmip` metodo per eliminare un server delle chiavi KMIP (Key Management Interoperability Protocol) esistente. È possibile eliminare un server chiavi a meno che non sia l'ultimo assegnato al proprio provider e il provider non stia fornendo chiavi attualmente in uso.



[[parameters]]
== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
KeyServerID
 a| 
L'ID del server chiavi KMIP da eliminare.
 a| 
intero
 a| 
Nessuno
 a| 
Sì

|===


[[return-values]]
== Valori restituiti

Questo metodo non ha valori restituiti. L'operazione di eliminazione viene considerata corretta se non si verificano errori.



[[request-example]]
== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "DeleteKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


[[response-example]]
== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
   "id": 1,
   "result":
      {}
}
----


[[new-since-version]]
== Novità dalla versione

11,7
